<?php
/**
 * @file
 * Contains chat_access.module.
 */

use Drupal\chat_access\Controller\ChatAccessController;
use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use \Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Drupal\Core\Entity\EntityInterface;

// function themeDump($var) {
//   $var_dumper = '\Symfony\Component\VarDumper\VarDumper';
//   if (class_exists($var_dumper)) {
//     call_user_func($var_dumper . '::dump', $var);
//   }
//   else {
//     trigger_error('Could not dump the variable because symfony/var-dumper component is not installed.', E_USER_WARNING);
//   }
// }

/**
 * Implementation of hook_help().
 */
function chat_access_help( $path, $arg )
{
    // switch ( $path )
    // {
    //     case 'admin/help#fbauth_auth':
    //     {
    //         return( '<p>' . t('This module allows users who login with e-mail addresses to authenticate off of external.') . '</p>' );
    //     }
    // }
}

?>
